"""
Fallback recording builder — Agent 2 (integration).

Captures connect() + underwrite() for all 3 personas into the OFFLINE artifacts the
frontend runs from with no backend / no network (Contract 3):
    data/fallback-recording.json   (served over http / programmatic)
    data/fallback-recording.js     (window.FALLBACK_RECORDING — for file:// double-click)

Prefers Agent 1's canonical engine when importable; else uses the A2 reference.
Regenerate whenever the engine output changes.  Run:
    python data/make_fallback.py
"""
from __future__ import annotations
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import personas as P  # noqa: E402
import generate  # noqa: E402

_BACKEND = os.path.join(os.path.dirname(HERE), "backend")
sys.path.insert(0, _BACKEND)
try:
    from underwrite import underwrite  # type: ignore
    ENGINE = "backend/underwrite.py (Agent 1, canonical)"
except Exception:
    from reference_underwrite import underwrite  # noqa: E402
    ENGINE = "data/reference_underwrite.py (Agent 2 reference — swap when A1 engine lands)"


def build_record() -> dict:
    connect, uw = {}, {}
    for pid in P.PROFILES:
        bundle = generate.build_bundle(pid)
        connect[pid] = bundle
        uw[pid] = underwrite(bundle)
    return {
        "generated_seed": P.MASTER_SEED,
        "engine": ENGINE,
        "personas": P.PERSONA_LIST,
        "connect": connect,
        "underwrite": uw,
    }


def main():
    rec = build_record()
    json_path = os.path.join(HERE, "fallback-recording.json")
    js_path = os.path.join(HERE, "fallback-recording.js")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(rec, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by data/make_fallback.py — do not edit by hand. */\n")
        f.write("window.FALLBACK_RECORDING = ")
        json.dump(rec, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    print(f"engine: {ENGINE}")
    for pid in P.PROFILES:
        r = rec["underwrite"][pid]
        print(f"  {pid:<20} limit={r['limit_sar']:>7,} {r['structure']:<9} conf={r['confidence']}")
    print(f"\nwrote {json_path}")
    print(f"wrote {js_path}")


if __name__ == "__main__":
    main()
